import type { Learning, RunRecord } from "@/lib/types";
import { GTM_LOOP } from "@/lib/spec";
import { streamText } from "@/lib/anthropic";
import { ingest, synthesizeSignals, parseRawContext } from "@/engine/sensor";
import { policyPrompt, parsePlan } from "@/engine/policy";
import { parseActions, actLive } from "@/engine/tools";
import { gatePrompt, parseGate } from "@/engine/gate";
import { learningPrompt, parseLearnings } from "@/engine/learning";
import { loadMemory, saveRun, appendMemory, saveSpec } from "@/lib/store";

export const runtime = "nodejs";
export const maxDuration = 120;

const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || "default";

/**
 * Streams one full loop run as NDJSON events so the UI can render the 5 stages
 * live with a chat-typing effect:
 *   {type:"signals"}              sensor done
 *   {type:"stage",phase:"start"}  a stage began
 *   {type:"token"}                an Opus text delta (the typing effect)
 *   {type:"stage",phase:"done"}   a stage finished (carries parsed data)
 *   {type:"done", record}         the whole RunRecord
 */
export async function POST(req: Request) {
  let priorLearnings: Learning[] = [];
  let humanEdit: string | undefined;
  let spec = GTM_LOOP;
  let custom = false;
  let loopId = "default";
  let rawContext = "";
  let live = false; // when true, the tools layer performs real side-effects
  try {
    const body = await req.json();
    if (Array.isArray(body?.priorLearnings)) priorLearnings = body.priorLearnings;
    if (typeof body?.humanEdit === "string") humanEdit = body.humanEdit;
    if (typeof body?.rawContext === "string") rawContext = body.rawContext;
    if (body?.live === true) live = true;
    // A loop generated by the builder can run through the same engine.
    if (body?.spec?.name && Array.isArray(body.spec.sensors)) {
      spec = body.spec;
      custom = true;
    }
    loopId = typeof body?.loopId === "string" && body.loopId ? slug(body.loopId) : slug(spec.name);
  } catch {
    /* empty body is fine */
  }

  // Real-context mode: if the user pasted their actual week, ingest THAT.
  const realSignals = parseRawContext(rawContext);
  const useReal = realSignals.length > 0;

  // If the client passed no memory, fall back to durable store memory so a
  // run improves on prior runs even in a fresh session (best-effort on Vercel).
  if (priorLearnings.length === 0) {
    try {
      priorLearnings = await loadMemory(loopId);
    } catch {
      /* store unavailable — proceed with empty memory */
    }
  }

  const ts = new Date().toISOString();
  const encoder = new TextEncoder();

  const stream = new ReadableStream({
    async start(controller) {
      const send = (obj: unknown) =>
        controller.enqueue(encoder.encode(JSON.stringify(obj) + "\n"));
      const tokens = (stage: string) => (text: string) => send({ type: "token", stage, text });

      try {
        // 1) SENSOR — real pasted context wins, else synth (custom) / fixtures.
        send({ type: "stage", stage: "sensor", phase: "start" });
        const signals = useReal
          ? realSignals
          : custom
            ? await synthesizeSignals(spec)
            : await ingest(spec.sensors);
        send({ type: "signals", signals });
        send({ type: "stage", stage: "sensor", phase: "done", data: { count: signals.length, real: useReal } });

        // 2) POLICY (streamed)
        send({ type: "stage", stage: "policy", phase: "start", data: { priorLearningCount: priorLearnings.length } });
        const p = policyPrompt(signals, spec, priorLearnings, humanEdit);
        const output = await streamText({ ...p, onToken: tokens("policy") });
        send({ type: "stage", stage: "policy", phase: "done" });

        // 3) TOOLS — real side-effects when live + connector configured, else dry-run.
        send({ type: "stage", stage: "tools", phase: "start" });
        const outcomes = await actLive(parseActions(output), live);
        send({ type: "stage", stage: "tools", phase: "done", data: { outcomes, live } });

        // 4) GATE (streamed)
        send({ type: "stage", stage: "gate", phase: "start" });
        const g = gatePrompt(output, spec.rubric, priorLearnings.length);
        const gateText = await streamText({ ...g, onToken: tokens("gate"), maxTokens: 700 });
        const gate = parseGate(gateText, priorLearnings.length);
        send({ type: "stage", stage: "gate", phase: "done", data: { score: gate.score, pass: gate.pass, criteria: gate.criteria } });

        // 5) LEARNING (streamed)
        send({ type: "stage", stage: "learning", phase: "start" });
        const l = learningPrompt({ spec, output, gateText, score: gate.score, humanEdit });
        const learnText = await streamText({ ...l, onToken: tokens("learning"), maxTokens: 500 });
        const learnings = parseLearnings(learnText, ts);
        send({ type: "stage", stage: "learning", phase: "done", data: { learnings } });

        const record: RunRecord = {
          ts,
          signals,
          plan: parsePlan(output),
          outcomes,
          output,
          gate,
          learnings,
          priorLearningCount: priorLearnings.length,
        };

        // Persist the run + new learnings durably (best-effort: a read-only FS
        // on serverless must never break the stream the user is watching).
        try {
          await saveRun(record, loopId, "manual");
          await appendMemory(learnings, loopId);
          if (custom) await saveSpec(spec, loopId);
        } catch {
          /* persistence is best-effort */
        }

        send({ type: "done", record });
      } catch (err) {
        send({ type: "error", message: err instanceof Error ? err.message : String(err) });
      } finally {
        controller.close();
      }
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type": "application/x-ndjson; charset=utf-8",
      "Cache-Control": "no-cache, no-transform",
      Connection: "keep-alive",
    },
  });
}
