import type { LoopSpec } from "@/lib/types";
import { designFromSpec } from "./architect";

/**
 * CODEGEN AGENT (builder 3/3)
 * Emits a runnable Claude Code project from the LoopSpec — the artifact the
 * user keeps. Deterministic template-fill (PLAN.md §13): a fixed scaffold where
 * the spec is interpolated into the policy, rubric, and tool wiring. No model
 * call, so it's instant and never produces broken code.
 */

export interface GeneratedFile {
  path: string;
  content: string;
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

export function generateRepo(spec: LoopSpec): GeneratedFile[] {
  const name = slug(spec.name) || "operating-loop";
  const { rubricMd } = designFromSpec(spec);

  const claudeMd = [
    `# ${spec.name}`,
    ``,
    `> ${spec.description}`,
    ``,
    `A self-improving operating loop generated by Loopsmith. It runs the closed loop:`,
    `**sensor → policy → tools → gate → learning** — and gets better every run.`,
    ``,
    `## How it runs`,
    `- **Cadence:** \`${spec.cadence}\` (a scheduler fires \`npm run loop\` on this cadence).`,
    `- **Sensors:** ${spec.sensors.join(", ")} (via MCP connectors).`,
    `- **Decision policy:** ${spec.decisionPolicy}`,
    `- **Output:** ${spec.outputFormat}`,
    `- **Gate:** every result is graded against \`rubric.md\`; below 80/100 it is held for review.`,
    `- **Memory:** durable lessons in \`memory/\` are read first on each run.`,
    ``,
    `## Layers`,
    `| Layer | Job | File |`,
    `|---|---|---|`,
    `| Sensor | ingest + normalize signals | \`engine/sensor.ts\` |`,
    `| Policy | decide what matters (Opus 4.8) | \`engine/policy.ts\` |`,
    `| Tools | take action (dry-run by default) | \`engine/tools.ts\` |`,
    `| Gate | grade vs \`rubric.md\` (Opus 4.8) | \`engine/gate.ts\` |`,
    `| Learning | reflect → \`memory/\` (Opus 4.8) | \`engine/learning.ts\` |`,
    ``,
    `## Run`,
    `\`\`\`bash`,
    `export ANTHROPIC_API_KEY=...   # Opus 4.8`,
    `npm install`,
    `npm run loop                   # one run`,
    `\`\`\``,
    ``,
    `Generated by Loopsmith · powered by Claude Opus 4.8.`,
  ].join("\n");

  const runbook = [
    `# Runbook — ${spec.name}`,
    ``,
    `## What this does`,
    `${spec.description}`,
    ``,
    `## The loop, in plain English`,
    `1. **Listens** to ${spec.sensors.join(", ")}.`,
    `2. **Decides** what matters: ${spec.decisionPolicy}`,
    `3. **Acts**: ${spec.outputFormat} (drafts you review).`,
    `4. **Checks** the result against the quality bar (see rubric.md).`,
    `5. **Learns** your preferences and applies them next time.`,
    ``,
    `## Schedule`,
    `Runs \`${spec.cadence}\`. Toggle off anytime; nothing sends without your OK while in dry-run.`,
    ``,
    `## What "done" means (verifiable by the model, no human)`,
    `- \`npm run loop\` exits 0 and writes \`runs/<ts>/output.md\` + \`runs/<ts>/gate.json\`.`,
    `- The gate score is present and numeric.`,
    `- A new lesson appears in \`memory/\` (or the score is non-decreasing on fixed input).`,
  ].join("\n");

  const pkg = JSON.stringify(
    {
      name,
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: { loop: "tsx engine/run.ts" },
      dependencies: { "@anthropic-ai/sdk": "^0.104.1", tsx: "^4.0.0" },
    },
    null,
    2,
  );

  return [
    { path: "loop-spec.json", content: JSON.stringify(spec, null, 2) },
    { path: "CLAUDE.md", content: claudeMd },
    { path: "rubric.md", content: rubricMd },
    { path: "RUNBOOK.md", content: runbook },
    { path: "package.json", content: pkg },
  ];
}
